name: Validate asana link presence

on:
  pull_request:
    types: [opened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: everphone-gmbh/github-asana-action@385529c
        with:
          asana-pat: ${{ secrets.ASANA }}
          action: '[assert-link, edited]'
          github-token: ${{ secrets.GITHUB }}
